### ISSUE TITLE
Not running with Angular 10

### ISSUE THREAD

**Issue by hervehobbes** [omridevk/ng-keyboard-shortcuts#90]
**Describe the bug**
After adding the required code in app.module.ts I have an error message from the compiler:
`
ERROR in ./node_modules/ng-keyboard-shortcuts/__ivy_ngcc__/fesm2015/ng-keyboard-shortcuts.js
Module build failed: Error: ENOENT: no such file or directory, open '....\node_modules\ng-keyboard-shortcuts\__ivy_ngcc__\fesm2015\ng-keyboard-shortcuts.js'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Storage.provideSync (.....\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync (.....\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Observable._subscribe (.....\node_modules\@ngtools\webpack\src\webpack-input-host.js:36:51)
    at Observable._trySubscribe (.....\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (.....\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (.....\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:25:20)
    at SyncDelegateHost.read (.....\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:48:21)
    at WebpackCompilerHost.readFileBuffer (.....\node_modules\@ngtools\webpack\src\compiler_host.js:166:44)
    at VirtualFileSystemDecorator.readFile (.....\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:43:54)
    at processResource (.....\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (.....\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (.....\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (.....\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (.....\node_modules\webpack\lib\NormalModule.js:446:15)

    ERROR in node_modules/ng-keyboard-shortcuts/lib/ng-keyboard-shortcuts.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (ng-keyboard-shortcuts) which declares KeyboardShortcutsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    2 export declare class KeyboardShortcutsModule {
`

**To Reproduce**
1.Create an Angular v10 project and install the library
2. Compile the project

**Expected behavior**
A running version ??

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Angular Version: 10.0.12

**Comment by omridevk** [comment]
Thank you for reporting the issue.
I seem to have compiled the latest release with the wrong angular compiler for some reason my node modules was not up to date.
Will release a new version in couple of minutes to fix this.

**Comment by omridevk** [comment]
@hervehobbes 
I have released version
10.1.16
please let me know if the issue persist.

**Comment by hervehobbes** [comment]
It's running perfectly, thank you very much.
